AllCops:
  TargetRubyVersion: 2.4

Naming/FileName:
  Exclude:
    - 'r18n-core/lib/r18n-core/locales/*.rb'
    - 'r18n-core/spec/locales/*.rb'
    - '**/r18n-core.rb'
    - '**/r18n-rails.rb'
    - '**/r18n-rails-api.rb'
    - '**/r18n-desktop.rb'
    - '**/r18n-desktop_spec.rb'
    - '**/sinatra-r18n.rb'
    - '**/sinatra-r18n_spec.rb'

Style/AsciiComments:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineArrayBraceLayout:
  EnforcedStyle: new_line
Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent
Layout/IndentFirstArgument:
  EnforcedStyle: consistent
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*'
    - 'benchmark/*'

Style/NumericLiterals:
  Exclude:
    - '**/db/**/*'

# TODO: fix offenses and enable cops

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false
  Exclude:
    - '**/spec/**/*'
